[package]
name = "rano"
version = "0.1.0"
edition = "2024"
description = "rano (short for rust_agent_network_observer): AI CLI network observer"

[features]
default = []

[dependencies]
libc = "0.2"
rusqlite = { version = "0.32", features = ["bundled"] }
